#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/net-daemon/netdaemon
  # -- image tag
  tag: dev
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See [docs](https://netdaemon.xyz/docs/started/installation#evironment-variables) for more details.
# @default -- See below
env:
  NETDAEMON__APPSOURCE: /data
  NETDAEMON__ADMIN: false
  NETDAEMON__GENERATEENTITIES: false
  # HOMEASSISTANT__HOST:
  # HOMEASSISTANT__PORT:
  # HOMEASSISTANT__TOKEN:

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 5000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: false
    mountPath: /data
